[package]
name = "pallet-blocktime-runtime-api"
version = "2.0.1"
authors = ['Rafal Piotrowski']
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
sp-api = { version = '2.0.1', default-features = false}

[dev-dependencies]
serde_json = "1.0.41"

[features]
default = ["std"]
std = [
	"sp-api/std",
]
